import './globals.css'
import type { Metadata } from "next";
import { Sora } from 'next/font/google'
import { AuthProvider } from '../firebase/context/AuthContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  variable: '--font-sora',
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sora.variable}>
      <body><AuthProvider>{children}</AuthProvider></body>
    </html>
  )
}
